//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nourhatem_522082
{
    using System;
    using System.Collections.Generic;
    
    public partial class userr
    {
        public int u_id { get; set; }
        public string u_password { get; set; }
        public string name { get; set; }
        public Nullable<int> u_age { get; set; }
        public string gender { get; set; }
        public string phone { get; set; }
        public string city { get; set; }
    }
}
